### ISSUE TITLE
Can't equip Backpack

### ISSUE THREAD

**Issue by Lovinoes** [Tiviacz1337/Travelers-Backpack#1260]
## MODLOADER AND MOD VERSION
**Mod Loader**: Forge 1.20.1-47.4.0
**Mod Version**: 9.1.35

## Describe the bug
It is impossible to equip a Backpack, there is no button for it or whatsoever.

## Steps to reproduce
1. Install the mod using version 9.1.35
2. Add following mods:
<details>
<summary>Modlist (Click to expand)</summary>

- **[3d-Skin-Layers](https://modrinth.com/mod/zV5r3pPn) [1.7.5]** by  tr7zw
- **[AppleSkin](https://modrinth.com/mod/EsAfCjCV) [2.5.1+mc1.20.1]** by  squeek
- **[Applied Energistics 2](https://modrinth.com/mod/XxWD5pD3) [15.3.4]** by  TeamAppliedEnergistics
- **[Applied Mekanistics](https://modrinth.com/mod/IiATswDj) [1.4.2]** by  ramidzkh
- **[Architectury](https://modrinth.com/mod/lhGA9TYQ) [9.2.14]** by  shedaniel
- **[Bad Packets](https://modrinth.com/mod/ftdbN0KK) [0.4.3]** by  deirn
- **[Balm](https://modrinth.com/mod/MBAkmtvl) [7.3.27]** by  BlayTheNinth
- **[Baubley Heart Canisters](https://modrinth.com/mod/fPdy2fCM) [1.20.1-1.1.0]** by  Traverse_Joe
- **[Bobber Detector](https://www.curseforge.com/minecraft/mc-mods/fishing-bobber-detector) [0.1.9.1.20.1]** by  GLaD0S
- **[CC: Tweaked](https://modrinth.com/mod/gu7yAYhd) [1.115.0]** by  Daniel Ratcliffe, Aaron Mills, SquidDev
- **[Chat Heads](https://modrinth.com/mod/Wb5oqrBJ) [0.13.17]** by  dzwdz, Fourmisain
- **[Cloth Config v10 API](https://modrinth.com/mod/9s6osm5g) [11.1.136]** by  shedaniel
- **[CoFH Core](https://modrinth.com/mod/OWSRM4vD) [11.0.2]** by  King Lemming, Zeldo Kavira, covers1624, skyboy, Cynycal, Drullkus
- **[Continuity](https://modrinth.com/mod/1IjD5062) [3.0.0+1.20.1.forge]** by  PepperCode1
- **[Create](https://modrinth.com/mod/LNytGWDc) [0.5.1.j]** by  simibubi
- **[Create : Encased](https://modrinth.com/mod/hSSqdyU1) [1.20.1-1.6.2-fix3]** by  iglee42
- **[Create Chunkloading](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading) [1.6.0]** by  embeddedt
- **[Create Diesel Generators](https://modrinth.com/mod/ZM3tt6p1) [1.20.1-1.2i]** by  kamień-bot AKA George VI AKA Jesz
- **[Create Goggles](https://modrinth.com/mod/L1RT5SJc) [0.5.6]** by  Robocraft999
- **[Create Mechanical Extruder](https://modrinth.com/mod/hGAlcCDJ) [1.20.1-1.6.3.j-55]** by  
- **[Create: Copycats+](https://modrinth.com/mod/UT2M39wf) [2.2.2+mc.1.20.1-forge]** by  Lysine, Bennyboy1695, Redcat_XVIII
- **[Create: Design n' Decor](https://modrinth.com/mod/x49wilh8) [0.4.0b]** by  DrMangoTea, Milky, Luna, Pepa, Spydnel
- **[Create: Dreams & Desires](https://modrinth.com/mod/JmybsfWs) [0.1b.Release-Early-Dev]** by  LopyLuna
- **[Create: Easy Structures](https://modrinth.com/mod/z69Pxatv) [0.2]** by  Ma_Do
- **[Create: Framed](https://www.curseforge.com/minecraft/mc-mods/create-framed) [1.5.5]** by  DakotaPride
- **[Create: Oxidized](https://modrinth.com/mod/X9kjRZeX) [0.1.1]** by  Pyzpre
- **[CreateArmory](https://modrinth.com/mod/MIxwm5GN) [0.5]** by  dcchill
- **[Curios API](https://modrinth.com/mod/vvuO3ImH) [5.14.1+1.20.1]** by  C4
- **[Embeddium](https://modrinth.com/mod/sk9rgfiA) [0.3.31+mc1.20.1]** by  embeddedt
- **[Embeddium Extra](https://modrinth.com/mod/oY2B1pjg) [0.5.4.4+mc1.20.1-build.131]** by  dima_dencep, FlashyReese
- **[Entity Model Features](https://modrinth.com/mod/4I1XuqiY) [2.4.1]** by  Traben
- **[Entity Texture Features](https://modrinth.com/mod/BVzZfTc1) [6.2.9]** by  Traben
- **[EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.7.4]** by  tr7zw
- **[Extended Cogwheels](https://modrinth.com/mod/qO4lsa4Y) [2.1.1-1.20.1-0.5.1.f-forge]** by  Rabbitminers
- **[Fallingleaves](https://modrinth.com/mod/2JAUNCL4) [2.1.2]** by  Cheaterpaul, Fourmisain, BrekiTomasson and RandomMcSomethin
- **[Fast IP Ping](https://modrinth.com/mod/9mtu0sUO) [1.0.5]** by  Fallen_Breath
- **[Ferrite Core](https://modrinth.com/mod/uXXizFIs) [6.0.1]** by  malte0811
- **[Forgified Fabric API](https://modrinth.com/mod/Aqlf1Shp) [0.92.2+1.11.12+1.20.1]** by  FabricMC, Sinytra
- **[Framework](https://mrcrayfish.com/mods?id=framework) [0.7.12]** by  MrCrayfish
- **[Fusion](https://modrinth.com/mod/p19vrgc2) [1.2.7]** by  SuperMartijn642
- **[GeckoLib 4](https://modrinth.com/mod/8BmcQJ2H) [4.7.1.2]** by  Gecko, Eliot, AzureDoom, DerToaster, Tslat, Witixin
- **[Jade](https://modrinth.com/mod/nvQzSEkH) [11.13.1+forge]** by  Snownee
- **[Jade Addons](https://modrinth.com/mod/xuDOzCLy) [5.3.1+forge]** by  Snownee
- **[Just Enough Items](https://modrinth.com/mod/u6dRKJwZ) [15.20.0.106]** by  mezz
- **[Just Enough Resources](https://modrinth.com/mod/uEfK2CXF) [1.4.0.247]** by  way2muchnoise
- **[Kotlin for Forge](https://modrinth.com/mod/ordsPcFz) [hmeyC41q]** by  
- **[LanguageReload](https://modrinth.com/mod/4zpN0syd) [1.0.1]** by  HiedaCamellia
- **[Mantle](https://modrinth.com/mod/Cg6Uc79H) [1.11.44]** by  Slime Knights
- **[Mekanism](https://modrinth.com/mod/Ce6I4WUE) [10.4.15]** by  Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd
- **[Mekanism: Additions](https://modrinth.com/mod/a6F3uASn) [10.4.15]** by  Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd
- **[Mekanism: Generators](https://modrinth.com/mod/OFVYKsAk) [10.4.15]** by  Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd
- **[Mekanism: Tools](https://modrinth.com/mod/tqQpq1lt) [10.4.15]** by  Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd
- **[MrCrayfish's Furniture Mod: Refurbished](https://mrcrayfish.com/mods/furniture_refurbished) [1.0.12]** by  MrCrayfish
- **[Nature's Compass](https://modrinth.com/mod/fPetb5Kh) [1.20.1-1.11.2-forge]** by  ChaosTheDude
- **[No Chat Reports](https://modrinth.com/mod/qQyHxfxd) [1.20.1-v2.2.2]** by  Aizistral
- **[ObsidianUI](https://modrinth.com/mod/E0L8mfJZ) [0.2.3+mc1.20.1]** by  TexTrue, ThinkingStudio
- **[Oculus](https://modrinth.com/mod/GchcoXML) [1.8.0]** by  NanoLive, dima_dencep, coderbot, IMS212, Justsnoopy30, FoundationGames
- **[Ok Zoomer](https://modrinth.com/mod/aXf2OSFU) [5.4.0-beta.8]** by  Ennui Langeweile and Up
- **[Quark](https://modrinth.com/mod/qnQsVE2z) [4.0-461]** by  Vazkii, WireSegal, MCVinnyq, Sully
- **[RyoamicLights](https://modrinth.com/mod/reCfnRvJ) [0.2.3+mc1.20.1]** by  TexTrue, ThinkingStudio
- **[Simple Voice Chat](https://modrinth.com/mod/9eGKb6K1) [1.20.1-2.5.29]** by  Max Henkel
- **[Sinytra Connector](https://modrinth.com/mod/u58R1TMW) [e8hSZ4vp]** by  
- **[Storage Drawers](https://modrinth.com/mod/guitPqEi) [12.9.13]** by  Texelsaur
- **[SuperMartijn642's Config Library](https://modrinth.com/mod/LN9BxssP) [1.1.8]** by  SuperMartijn642
- **[SuperMartijn642's Core Lib](https://modrinth.com/mod/rOUBggPv) [1.1.18]** by  SuperMartijn642
- **[Tectonic](https://modrinth.com/mod/lWDHr9jE) [2.4.1]** by  Apollo
- **[The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) [4.3.2508]** by  Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus, Andromander, GizmoTheMoonPig, jodlodi
- **[Thermal Expansion](https://modrinth.com/mod/hmD6rrUJ) [11.0.1]** by  King Lemming
- **[Thermal Foundation](https://modrinth.com/mod/Xvg6q5Wp) [11.0.6]** by  King Lemming
- **[Tinkers' Construct](https://modrinth.com/mod/rxIIYO6c) [3.9.2.37]** by  Slime Knights
- **[WaveyCapes](https://modrinth.com/mod/kYuIpRLv) [1.5.2]** by  tr7zw
- **[Waystones](https://modrinth.com/mod/LOpKHB2A) [14.1.11]** by  BlayTheNinth
- **[Xaero's Minimap](https://modrinth.com/mod/1bokaNcj) [25.2.0]** by  xaero96
- **[Xaero's World Map](https://modrinth.com/mod/NcUtCpym) [1.39.4]** by  xaero96
- **[Zeta](https://modrinth.com/mod/MVARlG2f) [1.0-29]** by  Vazkii, quat, IThundxr, siuol, wiresegal, MehVahdJukaar
- **[chisels-and-bits](https://www.curseforge.com/minecraft/mc-mods/chisels-bits) [1.4.148]** by  OrionDevelopment
- **[spark](https://modrinth.com/mod/l6YH9Als) [1.10.53]** by  Luck

</details>

3. Start the game and join a Multiplayer or Singleplayer World
4. Craft and try equipping a Backpack
 
## Expected behaviour
Normally there should be a Button to equip the Backpack

## Screenshots

![Image](https://github.com/user-attachments/assets/990e4b7e-0911-4154-b42a-170dc7c4af19)

![Image](https://github.com/user-attachments/assets/42188749-894c-4513-8874-7363360c3f1d)

**Comment by Lovinoes** [comment]
You can download one of my pre configured profiles from my CDN:
https://cdn.lovinoes.de/azure/v2/

Use the .mrpack file for Modrinth or Prism Launcher, or the .zip file for the CurseForge Launcher.
This way you can easily import the profile and see the issue for yourself

**Comment by Lovinoes** [comment]
okay nvm, I figured out how to equip the backpack since I'm using Curious API
https://github.com/Tiviacz1337/Travelers-Backpack/wiki#equipunequip-backpack

but still, is there a way for the button to show up?

**Comment by Tiviacz1337** [comment]
The button will show if you disable the integration in config

**Comment by Lovinoes** [comment]
Where is the option to deactivate the integration? There is nothing related to it in my config

```toml

#Client-only settings
[client]
	#Whether the backpack icon should be visible in player's inventory
	showBackpackIconInInventory = true
	#Sends a message to the player on death with backpack coordinates
	sendBackpackCoordinatesMessage = true
	#Enables tool cycling via keybind (Default Z) + scroll combination, while backpack is worn
	enableToolCycling = true
	#Allows tool cycling using keybinding only (Default Z)
	disableScrollWheel = false
	#Enables tip, how to obtain a backpack, if there's no crafting recipe for it
	obtainTips = true
	#Render tools in tool slots on the backpack, while worn
	renderTools = true
	#Only for supporters, option to show/hide the Supporter Star Badge. If you want to receive the Supporter Star Badge, visit my Ko-fi page :)! - https://ko-fi.com/tiviacz1337
	showSupporterBadge = true

	#The position of the Overlay on the screen
	[client.overlay]
		#Enables tanks and tool slots overlay, while backpack is worn
		enableOverlay = true
		#Offsets to left side
		#Range: > -2147483648
		offsetX = 20
		#Offsets to up
		#Range: > -2147483648
		offsetY = 30
```
